name: Publish Docker image

on:
  push: {branches: master}
  # release:
  #   types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: jpn-wordnet-vis
    steps:
      - name: PrepareReg Names
        run: |
          echo "------"
          echo ${{ secrets.MY_CR_PAT }}
          echo ${{ env.IMAGE_NAME }}
          echo ${{ github.run_number }}
          ls
          pwd
          echo "------"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/hemingwaylee/${{ env.IMAGE_NAME }}:1.0.${{ github.run_number }}
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
        # uses: docker/build-push-action@v1
        # with:
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}
        #   # The registry name must match
        #   registry: docker.pkg.github.com
        #   # The repo name must match
        #   repository: HemingwayLee/japanese-wordnet-visualization/my-image
        #   tag_with_ref: true



# docker/build-push-action@v1 is not working anymore
# Input 'repository' has been deprecated with message: v2 is now available through docker/build-push-action@v2
