name: Publish Docker image

on:
  # Can not see the package on github, don't know why
  push: {branches: master}
  # release:
  #   types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF:10}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          # tags: <org-name>/<repo-name>/<app-name>:${{ env.IMAGE_TAG }}
          tags: ghcr.io/${{ github.repository_owner }}/jpn-wordnet-vis:${{ env.IMAGE_TAG }}
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
        # uses: docker/build-push-action@v1
        # with:
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}
        #   # The registry name must match
        #   registry: docker.pkg.github.com
        #   # The repo name must match
        #   repository: HemingwayLee/japanese-wordnet-visualization/my-image
        #   tag_with_ref: true



# docker/build-push-action@v1 is not working anymore
# Input 'repository' has been deprecated with message: v2 is now available through docker/build-push-action@v2
